/**
* @file This script is auto-generated by create-nitro-module and should not be edited.
*
 * @description This script applies a workaround for Android by modifying the '<ModuleName>OnLoad.cpp' file.
 * It sets the JNI descriptor to match the library's implementation class at dev.rnforge.inappupdates.
 * Without this, nitrogen would generate a descriptor targeting the Nitro spec class instead of the
 * handwritten implementation.
*
* @module create-nitro-module
*/
const path = require('node:path')
const { writeFile, readFile } = require('node:fs/promises')

const androidWorkaround = async () => {
  const androidOnLoadFile = path.join(
    process.cwd(),
    'nitrogen/generated/android',
    'InAppUpdatesOnLoad.cpp'
  )

  const str = await readFile(androidOnLoadFile, { encoding: 'utf8' })
  const result = str.replace(
    /kJavaDescriptor = "L[^"]+";/,
    'kJavaDescriptor = "Ldev/rnforge/inappupdates/HybridInAppUpdates;";'
  )
  await writeFile(androidOnLoadFile, result)
}
androidWorkaround()
